# qutebrowser theme - Generated from centralized theme system
# Source this in your config.py with: config.source('theme.py')

c.colors.completion.fg = '#2D4A3D'
c.colors.completion.odd.bg = '#F9F2DF'
c.colors.completion.even.bg = '#FDF6E3'
c.colors.completion.category.fg = '#286983'
c.colors.completion.category.bg = '#FDF6E3'
c.colors.completion.category.border.top = '#FDF6E3'
c.colors.completion.category.border.bottom = '#FDF6E3'
c.colors.completion.item.selected.fg = '#2D4A3D'
c.colors.completion.item.selected.bg = '#f4eeee'
c.colors.completion.item.selected.border.top = '#f4eeee'
c.colors.completion.item.selected.border.bottom = '#f4eeee'
c.colors.completion.item.selected.match.fg = '#d7827e'
c.colors.completion.match.fg = '#d7827e'
c.colors.completion.scrollbar.fg = '#9893a5'
c.colors.completion.scrollbar.bg = '#FDF6E3'

c.colors.contextmenu.disabled.bg = '#FDF6E3'
c.colors.contextmenu.disabled.fg = '#9893a5'
c.colors.contextmenu.menu.bg = '#FDF6E3'
c.colors.contextmenu.menu.fg = '#2D4A3D'
c.colors.contextmenu.selected.bg = '#f4eeee'
c.colors.contextmenu.selected.fg = '#2D4A3D'

c.colors.downloads.bar.bg = '#FDF6E3'
c.colors.downloads.start.fg = '#2D4A3D'
c.colors.downloads.start.bg = '#286983'
c.colors.downloads.stop.fg = '#2D4A3D'
c.colors.downloads.stop.bg = '#5E7270'
c.colors.downloads.error.fg = '#ED333B'

c.colors.hints.fg = '#FDF6E3'
c.colors.hints.bg = '#69756C'
c.colors.hints.match.fg = '#9893a5'

c.colors.keyhint.fg = '#2D4A3D'
c.colors.keyhint.suffix.fg = '#69756C'
c.colors.keyhint.bg = '#FDF6E3'

c.colors.messages.error.fg = '#2D4A3D'
c.colors.messages.error.bg = '#ED333B'
c.colors.messages.error.border = '#ED333B'
c.colors.messages.warning.fg = '#2D4A3D'
c.colors.messages.warning.bg = '#d7827e'
c.colors.messages.warning.border = '#d7827e'
c.colors.messages.info.fg = '#2D4A3D'
c.colors.messages.info.bg = '#FDF6E3'
c.colors.messages.info.border = '#FDF6E3'

c.colors.prompts.fg = '#2D4A3D'
c.colors.prompts.border = '#EBE4D6'
c.colors.prompts.bg = '#F9F2DF'
c.colors.prompts.selected.fg = '#2D4A3D'
c.colors.prompts.selected.bg = '#f4eeee'

c.colors.statusbar.normal.fg = '#2D4A3D'
c.colors.statusbar.normal.bg = '#FDF6E3'
c.colors.statusbar.insert.fg = '#FDF6E3'
c.colors.statusbar.insert.bg = '#5E7270'
c.colors.statusbar.passthrough.fg = '#FDF6E3'
c.colors.statusbar.passthrough.bg = '#286983'
c.colors.statusbar.private.fg = '#2D4A3D'
c.colors.statusbar.private.bg = '#FDF6E3'
c.colors.statusbar.command.fg = '#2D4A3D'
c.colors.statusbar.command.bg = '#FDF6E3'
c.colors.statusbar.command.private.fg = '#2D4A3D'
c.colors.statusbar.command.private.bg = '#FDF6E3'
c.colors.statusbar.caret.fg = '#FDF6E3'
c.colors.statusbar.caret.bg = '#B8713A'
c.colors.statusbar.caret.selection.fg = '#FDF6E3'
c.colors.statusbar.caret.selection.bg = '#B8713A'
c.colors.statusbar.progress.bg = '#286983'
c.colors.statusbar.url.fg = '#2D4A3D'
c.colors.statusbar.url.error.fg = '#ED333B'
c.colors.statusbar.url.hover.fg = '#4A7C59'
c.colors.statusbar.url.success.http.fg = '#9893a5'
c.colors.statusbar.url.success.https.fg = '#5E7270'
c.colors.statusbar.url.warn.fg = '#d7827e'

c.colors.tabs.bar.bg = '#FDF6E3'
c.colors.tabs.indicator.start = '#286983'
c.colors.tabs.indicator.stop = '#5E7270'
c.colors.tabs.indicator.error = '#ED333B'
c.colors.tabs.odd.fg = '#575279'
c.colors.tabs.odd.bg = '#FDF6E3'
c.colors.tabs.even.fg = '#575279'
c.colors.tabs.even.bg = '#FDF6E3'
c.colors.tabs.pinned.odd.fg = '#2D4A3D'
c.colors.tabs.pinned.odd.bg = '#FDF6E3'
c.colors.tabs.pinned.even.fg = '#2D4A3D'
c.colors.tabs.pinned.even.bg = '#FDF6E3'
c.colors.tabs.pinned.selected.odd.fg = '#2D4A3D'
c.colors.tabs.pinned.selected.odd.bg = '#EBE4D6'
c.colors.tabs.pinned.selected.even.fg = '#2D4A3D'
c.colors.tabs.pinned.selected.even.bg = '#EBE4D6'
c.colors.tabs.selected.odd.fg = '#2D4A3D'
c.colors.tabs.selected.odd.bg = '#EBE4D6'
c.colors.tabs.selected.even.fg = '#2D4A3D'
c.colors.tabs.selected.even.bg = '#EBE4D6'

c.colors.webpage.bg = '#FDF6E3'
