# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false
control_server_enable = false
control_server_port = 8100

[defaults]
kanata_executable = '/opt/homebrew/bin/kanata'
tcp_port = 5829
autorestart_on_crash = true

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]


[presets.'Homerow Mods']
kanata_config = '~/.config/kanata/kanata.kbd'
extra_args = []
autorun = true

[presets.'Homerow Mods (Sudo)']
kanata_executable = 'sudo'
kanata_config = ''
extra_args = ['/opt/homebrew/bin/kanata', '--cfg', '~/.config/kanata/kanata.kbd']
tcp_port = 5830
autorun = false
